### ISSUE TITLE
x-axis do not always update

### ISSUE THREAD

**Issue by ignacio82** [ignacio82/vizdraws#37]
@drcthal can you take a look at this?

![image](https://user-images.githubusercontent.com/1833309/57194589-96b63d00-6f16-11e9-96f3-40f4118fac51.png)

You can find the code to reproduce this on the [repo for the paper that we are writing.](https://git.ignacio.website/ignacio/practical_equivalency/blob/master/experiment_arms.Rmd)

**Comment by drcthal** [comment]
Good catch. It's a selector issue: the original design uses html ID tags, because it thought it could safely assume only one would exist at a time. But now that markdown has 2 graphs, so it's only grabbing the first when it selects based on ID (you can see when you change the arm5 graph, the axis on arm4 updates. I'll check out what a good fix would be.
