### ISSUE TITLE
width as percentage is not working

### ISSUE THREAD

**Issue by ignacio82** [ignacio82/vizdraws#40]
```r
plot1 <- IMPosterior(prior = rnorm(100000, mean = 0, sd = 1), 
                     posterior = rnorm(100000, mean = 0.5, sd = 0.25), 
                     MME = 0.2, threshold = 0.7, units = "standard deviations", width = "95%", height = "95%")

htmlwidgets::saveWidget(widget = plot1, file = "plot1.html", selfcontained = TRUE)

plot1
```

@drcthal can you take a look?

**Comment by drcthal** [comment]
Hi Ignacio - try the 'resizing' new branch in my fork, just remove the width and height options from where you create plot1. That new branch has a lot of resizing working (including not reanimating everything). But it will break some charts: right now it wants to fill it's space, but that doesn't interact well with some things, like shiny will give you a tiny plot by default now, and you have to specify width if you want it to not be stupid.

**Comment by ignacio82** [comment]
definitely a step in the right direction.

**Comment by drcthal** [comment]
Do you have time to talk tomorrow? I'm not sure where to go from here, as I don't have anything in mind for desired sizing behavior. The resizing seems to work, and now it's a matter of defaults. The default for shiny is definitely not good, as it waits for shiny to give a size, and shiny waits for it to give a size, so it gives in and makes a tiny plot. I can make it so when it is waiting for something else to give it a height it goes to something reasonable, like 400. But I'm not sure all the situations in which you use it, so that may backfire. In that case, forcing the user to give a size in shiny could work.

**Comment by ignacio82** [comment]
Yes, I would be happy to brainstorm a bit.
