### ISSUE TITLE
Default height argument failing in Shiny

### ISSUE THREAD

**Issue by maxpohlman** [ignacio82/vizdraws#46]
```
library(shiny)
ui <- fluidPage(
   
   actionButton('button', 'Show Modal'),
   fluidRow(
     IMPosterior::IMPosteriorOutput('chart')
   )
)

server <- function(input, output) {
  
  #Gets draws as a reactive value 
  draws <- eventReactive(input$button,{
    rnorm(1000, mean = 200, sd = 15)
  })
  
  # Renders Posterior Output Object
  output$chart <- IMPosterior::renderIMPosterior({
    IMPosterior::IMPosterior(posterior = draws())
  })
  # Renders Posterior Output Object
  output$modal_chart <- IMPosterior::renderIMPosterior({
    IMPosterior::IMPosterior(posterior = draws())
  })
  
  # Creates Modal
  observeEvent(input$button,{
    req(draws())
    showModal(modalDialog(
      title = paste0("Predictions for your school"),
      IMPosterior::IMPosteriorOutput('modal_chart'),
      easyClose = T,
      size = 'm'
    ))
  })
  
}

# Run the application 
shinyApp(ui = ui, server = server)
```

In [Line 159](https://github.com/ignacio82/IMPosterior/blob/0b6786b6b92e176344f72dfdd7021cb72fd97096/R/IMPosterior.R#L159), the default argument for 'height' is set to 100%. In shiny, this means it will fully vertically fill whatever container it's in. Most visual outputs in shiny are contained in fluidRow()s, or other wrappers for fluid page design. These rows are, by default, not very big. This '100%' is simply filling up the default fluidRow() height, which looks to be too cramped. I don't know how to properly get the [sizingPolicy](https://github.com/ignacio82/IMPosterior/blob/0b6786b6b92e176344f72dfdd7021cb72fd97096/R/IMPosterior.R#L138) to work as even if you pass `NULL` into height/width, it auto-converts `NULL` to `100%`

**Comment by ignacio82** [comment]
@drcthal any thoughts??

**Comment by drcthal** [comment]
I don't have a good sense of how to fix it, since sizingpolicy doesn't have a carveout for shiny. You can always add a height argument when you call IMPosteriorOutput, e.g. change your line 6 to be `IMPosterior::IMPosteriorOutput('chart',height='800px')` and line 31 to be `IMPosterior::IMPosteriorOutput('modal_chart', height='400px'),`. That's obviously not a great solution as now height is hardcoded.

**Comment by drcthal** [comment]
This relates to what I said in issue #40  "The resizing seems to work, and now it's a matter of defaults. The default for shiny is definitely not good, as it waits for shiny to give a size, and shiny waits for it to give a size, so it gives in and makes a tiny plot. I can make it so when it is waiting for something else to give it a height it goes to something reasonable, like 400. But I'm not sure all the situations in which you use it, so that may backfire. In that case, forcing the user to give a size in shiny could work."

@maxpohlman I don't know anything about Shiny - if you were putting a different graph in there, how would you normally make sure it was the right size?

**Comment by ignacio82** [comment]
@timelyportfolio any chance that you can point us in the right direction?

**Comment by maxpohlman** [comment]
Perhaps thinking too hard. It looks like the [default for shiny::plotOutput() is 400px](https://github.com/rstudio/shiny/blob/master/R/render-plot.R#L148). All of the fancy manipulation for getting other CSS parameters to work (such as `100%` and `auto`), should be also in the htmlwidgets package which we inherit from. I'm down to just go with the "industry standard", set the default to 400px, and call it a day.

**Comment by ignacio82** [comment]
if the "industry standard" is to set it to 400px, then we should have a very good reason to do something different or go with that. @drcthal what do you think we should do?

**Comment by drcthal** [comment]
In the new PR I changed so that if the height is given as 0, use 400 (rather than dimensions of parent). If width is 0, it uses the height (so 400 if both were 0). This fixes the modal in this example, but not the background plot. So it helps in some cases, but there will still be issues, and the general answer stays as 
"specify a height if it acts funny". I could also revert to the old way, were it was always 400px, but that will kill the scaling.
