### ISSUE TITLE
Non-increasing break values cause incorrect(?) output

### ISSUE THREAD

**Issue by maxpohlman** [ignacio82/vizdraws#47]
I would think the following lines of code would yield the same thing:
```
IMPosterior::IMPosterior(posterior = rnorm(1000, mean = 200, sd = 15), breaks = c(180, 220))

IMPosterior::IMPosterior(posterior =  rnorm(1000, mean = 200, sd = 15), breaks = c(220, 180))
```

However, the second one sets the lowest break at 220 and then puts no break at 180.

If this is unintended, maybe a `breaks <- sort(breaks)` should go somewhere in the code

**Comment by ignacio82** [comment]
Thanks for reporting this @maxpohlman. @drcthal is this something that you can fix?

**Comment by drcthal** [comment]
Good catch. I have a pull request with the breaks <- sort(breaks) fix. The one issue is what to do if you provide unordered breaks and also provide names/colors. For now I'm assuming breaks_names and colors are supplied in ascending order (and I added a warning about this if breaks is unsorted). I don't want to just put the names/colors in the same order as breaks because they have a longer length than breaks, so the order can be ambiguous (e.g. if breaks are c(2,3,1) and names are (a,b,c,d), I can't tell how to reorder names). I could add an exception if breaks are strictly descending then assume colors/names were provided in that order too, but I don't love that either.
